# Generated by Django 4.0 on 2022-01-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='market',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='market_cart', to='shop.market'),
            preserve_default=False,
        ),
    ]
