# Generated by Django 4.0 on 2022-01-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=10, max_length=10, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('like_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'حذف شده'), ('P', 'در دست بررسی')], max_length=1)),
                ('category', models.ManyToManyField(to='shop.Category')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market')),
                ('tag', models.ManyToManyField(to='shop.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment_post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
