# Generated by Django 4.0 on 2022-01-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'حذف شده'), ('P', 'در دست بررسی')], default='P', max_length=1)),
                ('type', models.CharField(choices=[('D', 'کالا های دیجیتال'), ('C', 'خودرو و ابزار و تجهیزات صنعتی'), ('M', 'مد و پوشاک'), ('K', 'اسباب بازی , کودک و نوزاد'), ('S', 'کالاهای سوپرمارکتی'), ('Z', 'زیبایی و سلامت'), ('P', 'خانه و آشپزخانه'), ('B', 'کتاب و لوازم تحریر و هنر'), ('V', 'ورزش و سفر'), ('H', 'محصولات بومی و محلی')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_market', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=12, max_length=12, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('number_product', models.PositiveIntegerField()),
                ('main_image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('like_count', models.IntegerField(default=0)),
                ('expire', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'حذف شده'), ('P', 'در دست بررسی')], max_length=1)),
                ('category', models.ManyToManyField(to='shop.Category')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market')),
                ('tag', models.ManyToManyField(to='shop.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.comment_product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
    ]
