# Generated by Django 4.0 on 2021-12-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'حذف شده'), ('P', 'در دست بررسی')], default='P', max_length=1),
        ),
    ]
